export const siteKeywords = [
    'Carboit',
    'DevLach',
    'Digital Marketing',
    'SEO',
    'Social Media',
    'Web Design',
    'Web Development',
    'Content Marketing',
    'Email Marketing',
    'shadcn',
    'tailwindcss',
    'nextjs',
    'typescript',
    'reactjs',
    'javascript',
    'software development',
    'digital transformation',
    'custom software solutions',
    'startup growth',
    'enterprise software development',
    'innovation',
    'operational excellence',
    'web development',
    'application development',
    'CMS customization',
    'tech consulting',
    'business scalability',
    'digital strategy',
    'technology solutions'
] as string[];
