export const siteKeywords = [
    'Carboit',
    'DevLach',
    'Marketing Digital',
    'SEO',
    'Redes Sociales',
    'Diseño Web',
    'Desarrollo Web',
    'Marketing de Contenidos',
    'Email Marketing',
    'shadcn',
    'tailwindcss',
    'nextjs',
    'typescript',
    'reactjs',
    'javascript',
    'desarrollo de software',
    'transformación digital',
    'soluciones de software personalizadas',
    'crecimiento de startups',
    'desarrollo de software empresarial',
    'innovación',
    'excelencia operativa',
    'desarrollo web',
    'desarrollo de aplicaciones',
    'personalización de CMS',
    'consultoría tecnológica',
    'escalabilidad empresarial',
    'estrategia digital',
    'soluciones tecnológicas',
    'estudio de desarrollo de software',
    'servicios de software personalizados',
    'paisaje digital',
    'estudio de desarrollo web',
    'innovación en el desarrollo de aplicaciones',
    'desarrollo de CMS',
    'consultoría tecnológica',
    'soluciones de software empresarial',
    'éxito de startups',
    'estudio de diseño web',
    'experiencia en desarrollo de software',
    'estrategia de marketing digital',
    'consultoría tecnológica',
    'crecimiento empresarial',
    'soluciones de desarrollo web',
    'servicios de desarrollo de aplicaciones',
    'servicios de personalización de CMS',
    'soluciones de escalabilidad empresarial',
    'consultoría en estrategia digital',
    'proveedor de soluciones tecnológicas',
    'desarrollo de startups',
    'consultoría en software empresarial',
    'innovación en desarrollo de software',
    'experiencia en marketing digital'
] as string[];

export const odooKeywords = [
    'odoo',
    'erp',
    'crm',
    'business management',
    'business software',
    'enterprise resource planning',
    'customer relationship management',
    'inventory management',
    'accounting software',
    'project management',
    'manufacturing',
    'sales management',
    'purchase management',
    'e-commerce',
    'website builder',
    'marketing automation',
    'human resource management',
    'business intelligence',
    'reporting',
    'business process automation',
    'business intelligence',
    'Business management software',
    'CRM for businesses',
    'Online accounting',
    'Efficient inventory management',
    'Digital marketing strategies',
    'Sales automation',
    'Purchasing optimization',
    'Manufacturing process improvement',
    'Integrated human resources management',
    'Customized business solutions',
    'Business growth',
    'Operational efficiency',
    'Enterprise management tools',
    'Innovative software solutions',
    'Technology consulting for businesses',
    'Business scalability',
    'Digital strategies for businesses',
    'Digital transformation',
    'Comprehensive technology solutions',
    'Enterprise application development',
    'Software development for businesses',
    'Gestión empresarial',
    'CRM para empresas',
    'Contabilidad en línea',
    'Gestión de inventario eficiente',
    'Estrategias de marketing digital',
    'Automatización de ventas',
    'Optimización de compras',
    'Mejora de procesos de fabricación',
    'Gestión integrada de recursos humanos',
    'Soluciones empresariales personalizadas',
    'Crecimiento empresarial',
    'Eficiencia operativa',
    'Herramientas de gestión empresarial',
    'Soluciones de software innovadoras',
    'Consultoría tecnológica para empresas',
    'Escalabilidad empresarial',
    'Estrategias digitales para empresas',
    'Transformación digital',
    'Soluciones tecnológicas integrales',
    'Desarrollo de aplicaciones empresariales'
] as string[];

export const contactPageKeywords = [
    'Contacto',
    'Contactar',
    'Carboit',
    'DevLach',
    'Tech Solutions',
    'Soluciones Tecnológicas',
    'Business Contact',
    'Contactar Empresa',
    'Digital Innovation',
    'Innovación Digital',
    'Business Growth',
    'Crecimiento Empresarial',
    'Software Development',
    'Desarrollo de Software',
    'Tech Consultation',
    'Consultoría Tecnológica',
    'Contact Form',
    'Formulario de Contacto',
    'Email Contact',
    'Contacto por Email',
    'Phone Contact',
    'Contacto por Teléfono',
    'Connect with Us',
    'Conéctate con Nosotros',
    'Tech Partnership',
    'Asociación Tecnológica',
    'Tech Collaboration',
    'Colaboración Tecnológica',
    'Turn Ideas into Reality',
    'Haz Realidad tus Ideas',
    'Cutting-edge Tech Solutions',
    'Soluciones Tecnológicas de Vanguardia',
    'Business Contact Information',
    'Información de Contacto Empresarial'
] as string[];

